#!/bin/sh
set -e

ln -sf "$PWD/.bashrc" "$HOME/.bashrc"
ln -sf "$PWD/.dir_colors" "$HOME/.dir_colors"
ln -sf "$PWD/.inputrc" "$HOME/.inputrc"
ln -sf "$PWD/.profile" "$HOME/.profile"
ln -sf "$PWD/.profile" "$HOME/.bash_profile"
ln -sf "$PWD/.Xresources" "$HOME/.Xresources"
ln -sd "$PWD/wofi/" "$HOME/.config/"
ln -sd "$PWD/wezterm/" "$HOME/.config/"
ln -sd "$PWD/i3/" "$HOME/.config/"
ln -sd "$PWD/sway/" "$HOME/.config/"
ln -sd "$PWD/i3blocks" "$HOME/.config/"

for i in vim lynx git tmux docker podman scripts ; do
  cd $i && ./setup
  cd -
done
